### PR TITLE
Make BerlinDB PSR-4 compatible

### PR DESCRIPTION
**Pull request by szepeviktor**
@JJJ More Alive!
Included autoloader.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Test the autoloader:

```php
<?php

define( 'ABSPATH', '' );
class WP_Meta_Query {}
require 'autoloader.php';
new BerlinDB\Database\Schema();
new BerlinDB\Database\Queries\Compare();
```

**Comment by Tabrisrp** [comment]
Couldn't it be autoloaded via composer directly by adding the `composer.json` file and the required directives?

**Comment by szepeviktor** [comment]
> Couldn't it be autoloaded via composer directly

Yes it could.
I've notices many projects load BerlinDB with `require`.

**Comment by danieliser** [comment]
@szepeviktor I believe this duplicates the work that was already merged into the release/2.0 branch: https://github.com/berlindb/core/pull/57

**Comment by szepeviktor** [comment]
Thank you.
Yes, it does.

**Pull request closed without merging**
