### PR TITLE
Fix types

### PR DESCRIPTION
**Pull request by szepeviktor**
I've started fixing types using @PHPStan.

But to be strictly typed we need will!
How about that?

### CODE REVIEW

**Comment by JJJ** [comment]
Many good improvements here.

I'd like to keep the `ABSPATH` checks on a single line, please.

**Comment by szepeviktor** [comment]
I do not problems with it.
You know I do this to practice using @phpstan and to blow off steam from client projects. So I close this one.

**Comment by JJJ** [comment]
@szepeviktor 🤕 No reason to close it. Everything else was good!

**Comment by szepeviktor** [comment]
I know. But @phpstan sees `defined( 'ABSPATH' ) || exit;` as left side is always true.

**Comment by szepeviktor** [comment]
Anyone may continue this work! :)

**Pull request closed without merging**
